# Node.js with React - Azure Pipeline
# Pipeline for a Node.js project using a MERN stack with React
# Includes steps for building, running tests, and analyzing code with SonarQube

trigger:
- develop

pool: TestAgent

steps:
# Step 1: Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Step 2: Run backend tests with Mocha and Chai
- script: |
    cd backend
    npm install   # Install backend dependencies
    npm test      # Run backend tests (Mocha/Chai)
  displayName: 'Run backend tests with Mocha and Chai'

# Step 2: Run frontend tests with Jest
- script: |
    cd frontend
    npm install   # Install frontend dependencies
    npm test      # Run frontend tests (Jest)
  displayName: 'Run frontend tests with Jest'