version: '3.8'

services:
  backend:
    image: anas1dev/mern-server:latest
    ports:
      - '3000:3000'
    env_file:
      - .env

  client:
    image: anas1dev/mern-client:latest
    ports:
      - '80:80'
